source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in mariabalsamo-cli-app.gemspec
gemspec

gem 'mariabalsamo-cli-app'
